name: CI/CD

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Deploy
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Create venv
              run: |
                  python3 -m venv venv
                  source venv/bin/activate
                  python3 -m pip install -r requirements.txt

            - name: Restart service
              run: sudo systemctl restart rsoccergoals.service
